# Generated by Django 3.2.25 on 2024-12-16 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('balance', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
